[2024-03-04 15:40:41.855392] INFO: interface_case_run: 当前模块 生成数据驱动所用数据
[2024-03-04 15:40:41.855777] INFO: interface_case_run: 全部args参数参数信息 , ()
[2024-03-04 15:40:41.855900] INFO: interface_case_run: 全部kwargs参数信息 , {}
[2024-03-04 15:40:41.856045] INFO: interface_case_run: 当前模块 解析测试用例文件
[2024-03-04 15:40:41.856152] INFO: interface_case_run: 全部args参数参数信息 , ('/Users/xiaozixi/Desktop/work_project/git_pro/jiekou-python3/testCase/test_case_data/case.xls',)
[2024-03-04 15:40:41.856246] INFO: interface_case_run: 全部kwargs参数信息 , {}
[2024-03-04 15:40:41.856434] INFO: interface_case_run: 打开测试用例失败，原因是:[Errno 2] No such file or directory: '/Users/xiaozixi/Desktop/work_project/git_pro/jiekou-python3/testCase/test_case_data/case.xls'
